[2023-06-19 20:06:59,474] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:55:51.283782+00:00 [queued]>
[2023-06-19 20:06:59,494] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:55:51.283782+00:00 [queued]>
[2023-06-19 20:06:59,494] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:06:59,494] {taskinstance.py:1377} INFO - Starting attempt 3 of 6
[2023-06-19 20:06:59,495] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:06:59,524] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_data> on 2023-06-19 19:55:51.283782+00:00
[2023-06-19 20:06:59,531] {standard_task_runner.py:52} INFO - Started process 183 to run task
[2023-06-19 20:06:59,537] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_weather', 'extract_data', 'manual__2023-06-19T19:55:51.283782+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/dag_weather.py', '--cfg-path', '/tmp/tmpleebjgo3', '--error-file', '/tmp/tmpcpfesaso']
[2023-06-19 20:06:59,539] {standard_task_runner.py:80} INFO - Job 44: Subtask extract_data
[2023-06-19 20:06:59,663] {task_command.py:371} INFO - Running <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:55:51.283782+00:00 [running]> on host 86fac14d7b7b
[2023-06-19 20:06:59,741] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-06-19 20:06:59,807] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=MariaRO
AIRFLOW_CTX_DAG_ID=dag_weather
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T19:55:51.283782+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-19T19:55:51.283782+00:00
[2023-06-19 20:06:59,809] {logging_mixin.py:115} INFO - ***************
[2023-06-19 20:06:59,809] {logging_mixin.py:115} INFO - 2023-06-19 2023-06-19T19:55:51.283782+00:00
[2023-06-19 20:06:59,819] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_weather.py", line 40, in extract_data
    end = datetime.strptime(exec_date, '%Y-%m-%d').date()
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  2023-06-19T19:55:51.283782+00:00
[2023-06-19 20:06:59,834] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather, task_id=extract_data, execution_date=20230619T195551, start_date=20230619T200659, end_date=20230619T200659
[2023-06-19 20:06:59,859] {standard_task_runner.py:97} ERROR - Failed to execute job 44 for task extract_data (unconverted data remains:  2023-06-19T19:55:51.283782+00:00; 183)
[2023-06-19 20:06:59,908] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-19 20:07:00,108] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
