[2023-06-19 20:17:02,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:47:44.857859+00:00 [queued]>
[2023-06-19 20:17:02,652] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:47:44.857859+00:00 [queued]>
[2023-06-19 20:17:02,653] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:17:02,653] {taskinstance.py:1377} INFO - Starting attempt 6 of 6
[2023-06-19 20:17:02,653] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:17:02,676] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_data> on 2023-06-19 19:47:44.857859+00:00
[2023-06-19 20:17:02,683] {standard_task_runner.py:52} INFO - Started process 226 to run task
[2023-06-19 20:17:02,686] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_weather', 'extract_data', 'manual__2023-06-19T19:47:44.857859+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/dag_weather.py', '--cfg-path', '/tmp/tmpfmad6z0y', '--error-file', '/tmp/tmpz2zgpa79']
[2023-06-19 20:17:02,688] {standard_task_runner.py:80} INFO - Job 54: Subtask extract_data
[2023-06-19 20:17:02,780] {task_command.py:371} INFO - Running <TaskInstance: dag_weather.extract_data manual__2023-06-19T19:47:44.857859+00:00 [running]> on host 9b7db2eaec37
[2023-06-19 20:17:02,855] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-06-19 20:17:02,898] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=MariaRO
AIRFLOW_CTX_DAG_ID=dag_weather
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T19:47:44.857859+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-19T19:47:44.857859+00:00
[2023-06-19 20:17:02,901] {logging_mixin.py:115} INFO - ***************
[2023-06-19 20:17:02,901] {logging_mixin.py:115} INFO - 2023-06-19 19
[2023-06-19 20:17:02,907] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_weather.py", line 41, in extract_data
    end = datetime.strptime(exec_date.split("T")[0], '%Y-%m-%d').date()
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  19
[2023-06-19 20:17:02,916] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=dag_weather, task_id=extract_data, execution_date=20230619T194744, start_date=20230619T201702, end_date=20230619T201702
[2023-06-19 20:17:02,932] {standard_task_runner.py:97} ERROR - Failed to execute job 54 for task extract_data (unconverted data remains:  19; 226)
[2023-06-19 20:17:02,939] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-19 20:17:02,998] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
