[2023-06-19 20:07:58,790] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T20:07:56.990906+00:00 [queued]>
[2023-06-19 20:07:58,804] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: dag_weather.extract_data manual__2023-06-19T20:07:56.990906+00:00 [queued]>
[2023-06-19 20:07:58,804] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:07:58,804] {taskinstance.py:1377} INFO - Starting attempt 1 of 6
[2023-06-19 20:07:58,804] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-06-19 20:07:58,828] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): extract_data> on 2023-06-19 20:07:56.990906+00:00
[2023-06-19 20:07:58,833] {standard_task_runner.py:52} INFO - Started process 220 to run task
[2023-06-19 20:07:58,840] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'dag_weather', 'extract_data', 'manual__2023-06-19T20:07:56.990906+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/dag_weather.py', '--cfg-path', '/tmp/tmpx0s9eai9', '--error-file', '/tmp/tmplmul4yr0']
[2023-06-19 20:07:58,841] {standard_task_runner.py:80} INFO - Job 46: Subtask extract_data
[2023-06-19 20:07:58,938] {task_command.py:371} INFO - Running <TaskInstance: dag_weather.extract_data manual__2023-06-19T20:07:56.990906+00:00 [running]> on host 86fac14d7b7b
[2023-06-19 20:07:59,011] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:202 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2023-06-19 20:07:59,084] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=MariaRO
AIRFLOW_CTX_DAG_ID=dag_weather
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-19T20:07:56.990906+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-19T20:07:56.990906+00:00
[2023-06-19 20:07:59,086] {logging_mixin.py:115} INFO - ***************
[2023-06-19 20:07:59,086] {logging_mixin.py:115} INFO - 2023-06-19 2023-06-19T20:07:56.990906+00:00
[2023-06-19 20:07:59,093] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_weather.py", line 40, in extract_data
    end = datetime.strptime(exec_date, '%Y-%m-%d').date()
  File "/usr/local/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.7/_strptime.py", line 362, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains:  2023-06-19T20:07:56.990906+00:00
[2023-06-19 20:07:59,106] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_weather, task_id=extract_data, execution_date=20230619T200756, start_date=20230619T200758, end_date=20230619T200759
[2023-06-19 20:07:59,125] {standard_task_runner.py:97} ERROR - Failed to execute job 46 for task extract_data (unconverted data remains:  2023-06-19T20:07:56.990906+00:00; 220)
[2023-06-19 20:07:59,169] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-06-19 20:07:59,301] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
